version: "3.8"

services:
  db:
    image: postgres:15
    container_name: anomaly_postgres
    environment:
      POSTGRES_USER: anomaly_user
      POSTGRES_PASSWORD: anomaly_password
      POSTGRES_DB: anomaly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
